config/routes.rb
Rails.application.routes.draw do
  # Devise routes for authentication
  devise_for :users

  root to: "projects#index"
  
  resources :projects do
    collection do
      get :archived
    end

    member do
      patch :publish
      patch :archive
      patch :revert_to_draft
      post :upload_files
      delete :delete_file
    end

    resources :questions, except: [:index, :show]

    resources :ratings, only: [:create], defaults: { format: :json }

    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "creator_id"
    has_many :ratings
    has_many :questions, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many_attached :files

    validates :title, :description, :data_url, :status, presence: true
  end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_creator!, except: [:index, :show, :archived] 

  def index
    if current_user.role == 'expert'
      @projects = Project.where(status: 'published')
    else
      status_filter = params[:status] 
      if status_filter.present?
        @projects = current_user.created_projects.where(status: status_filter)
      else
        @projects = current_user.created_projects
      end
    end
  end
  
  def archived
    @projects = current_user.created_projects.where(status: 'archived')
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.created_projects.build(project_params)
    @project.status = 'draft'

    if @project.save
      redirect_to projects_path, notice: 'Проект успешно создан.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    if current_user.role == 'expert'
      @project = Project.find(params[:id])
    else
      @project = current_user.created_projects.find(params[:id])
    end
  end
  
  def edit
    @project = current_user.created_projects.find(params[:id])
  end
  
  def update
    @project = current_user.created_projects.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Проект обновлён."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: 'Проект успешно удален.'
  end
  
  def submit_for_review
    @project = current_user.created_projects.find(params[:id])
    @project.update(status: 'published')
    redirect_to project_path(@project), notice: "Проект отправлен на оценку."
  end
  
  def publish
    project = current_user.created_projects.find(params[:id])
    project.update(status: 'published')
    redirect_to project_path(project), notice: "Проект опубликован."
  end
  
  def archive
    project = current_user.created_projects.find(params[:id])
    project.update(status: 'archived')
    redirect_to project_path(project), notice: "Проект архивирован."
  end
  
  def revert_to_draft
    project = current_user.created_projects.find(params[:id])
    project.update(status: 'draft')
    redirect_to project_path(project), notice: "Проект возвращён в подготовку."
  end  

  def delete_file
    @project = Project.find(params[:id])
    file = @project.files.find(params[:file_id])
    file.purge
    redirect_to edit_project_path(@project), notice: "Файл удален"
  end
   
  def upload_files
    @project = Project.find(params[:id])
    if params[:files]
      params[:files].each do |file|
        @project.files.attach(file)
      end
    end
    redirect_to edit_project_path(@project), notice: "Файлы загружены"
  end

  private

  def require_creator!
    redirect_to root_path, alert: 'Доступ запрещен.' unless current_user.role == 'creator'
  end

  def require_expert!
    redirect_to root_path, alert: 'Только для экспертов' unless current_user.role == 'expert'
  end

  def project_params
    params.require(:project).permit(:title, :description, :data_url, files: [])
  end  

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.erb
<div class="container mt-5">
  <%= form_with model: @project, local: true do |f| %>
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h2 class="mb-0"><%= t('project.edit.title') %></h2>
      <%= f.submit t('project.edit.btn_save'), class: "btn btn-success" %>
    </div>

    <div class="mb-3">
      <%= f.label :title, t('project.edit.label_name') %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :description, t('project.edit.label_description') %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :data_url, t('project.edit.label_data_link') %>
      <%= f.url_field :data_url, class: "form-control" %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form_with url: upload_files_project_path(@project), method: :post, local: true, html: { multipart: true }, id: "file-upload-form" do |f| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= f.label :files, t('project.edit.label_new_files') %>
      <%= f.file_field :files, multiple: true, class: "form-control", onchange: "this.form.submit();" %>
    <% end %>
  </div>
  
  <% if @project.files.attached? %>
      <ul class="list-group mb-3">
        <% @project.files.each do |file| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= link_to file.filename.to_s, url_for(file), target: "_blank" %>
            <%= button_to t('project.edit.btn_del_file'), delete_file_project_path(@project, file_id: file.id), method: :delete, data: { confirm: "Удалить файл?" }, class: "btn btn-sm btn-outline-danger" %>
          </li>
        <% end %>
      </ul>
  <% end %>
</div>

app/views/projects/index.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2><%= t('projects.index.title') %></h2>
    <% if current_user.role == 'creator' %>
      <%= link_to t('projects.index.btn_add_project'), new_project_path, class: "btn btn-success" %>
    <% end %>
  </div>
  <% if current_user.role == 'creator' %>
  <div class="mb-3">
    <%= form_with url: projects_path, method: :get, local: true, class: "d-flex" do |form| %>
      <%= hidden_field_tag :locale, I18n.locale %>
      
      <%= form.select :status,
          options_for_select([
            [t('projects.index.filter_options.in_preparation'), 'draft'],
            [t('projects.index.filter_options.published'), 'published'],
            [t('projects.index.filter_options.archive'), 'archived']
          ], params[:status]),
          { prompt: t('projects.index.filter_options.all') },
          class: "form-select" %>

      <%= form.submit t('projects.index.btn_filter'), class: "btn btn-primary ms-2" %>
    <% end %>
  </div>

  <% end %>
  <% if @projects.any? %>
    <div class="list-group">
      <% @projects.each do |project| %>
        <%= link_to project_path(project), class: "list-group-item list-group-item-action" do %>
            <strong><%= project.title %></strong><br>
            <span class="badge 
                <%=
                  case project.status
                  when 'draft' then 'bg-warning'
                  when 'published' then 'bg-success'
                  when 'archived' then 'bg-secondary'
                  else 'bg-light text-dark'
                  end
                %>">
                <%=
                  case project.status
                  when 'draft' then t('projects.index.filter_options.in_preparation')
                  when 'published' then t('projects.index.filter_options.published')
                  when 'archived' then t('projects.index.filter_options.archive')
                  else t('projects.index.filter_options.unknown')
                  end
                %>
            </span>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <p class="text-muted"><%= t('projects.index.label_no_projects') %></p>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container mt-5">
  <%= link_to '←' + t('project.show.btn_back'), projects_path, class: "btn btn-outline-secondary" %>
  <h2 class="mt-2"><%= t('project.new.title') %></h2>

  <%= form_with model: @project, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :title, t('project.new.label_name') %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :description, t('project.new.label_description') %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :data_url, t('project.new.label_data_link') %>
      <%= f.url_field :data_url, class: "form-control" %>
    </div>

    <%= f.submit t('project.new.btn_save'), class: "btn btn-success" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container mt-5">
  <div class="mt-4 mb-4">
    <%= link_to '←' + t('project.show.btn_back'), projects_path, class: "btn btn-outline-secondary" %>
  </div>

  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2><%= @project.title %></h2>
    <% if current_user.role == 'creator' %>
      <div class="d-flex">
        <%= link_to t('project.show.btn_edit_project'), edit_project_path(@project), class: "btn btn-outline-warning me-2" %>
        <%= button_to t('project.show.btn_del_project'), project_path(@project), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить этот проект?' }, class: "btn btn-outline-danger me-2" %>
      </div>
    <% end %>
  </div>

  <p><strong><%= t('project.show.label.description') %>:</strong></p>
  <p><%= simple_format(@project.description) %></p>

  <p><strong><%= t('project.show.label.link') %>:</strong>
    <%= link_to @project.data_url, @project.data_url, target: "_blank", rel: "noopener", class: "btn btn-sm btn-outline-primary ms-2" %>
  </p>

  <p><strong><%= t('project.show.label.status') %>:</strong> 
    <span class="badge 
        <%=
          case @project.status
          when 'draft' then 'bg-warning'
          when 'published' then 'bg-success'
          when 'archived' then 'bg-secondary'
          else 'bg-light text-dark'
          end
        %>">
        <%=
          case @project.status
          when 'draft' then t('projects.index.filter_options.in_preparation')
          when 'published' then t('projects.index.filter_options.published')
          when 'archived' then t('projects.index.filter_options.archive')
          else t('projects.index.filter_options.unknown')
          end
        %>
    </span>
  </p>

  <% if @project.files.attached? %>
    <p><strong><%= t('project.show.label_files') %></strong></p>
    <ul class="list-group mb-3">
      <% @project.files.each do |file| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div>
            <% file_extension = File.extname(file.filename.to_s).downcase %>

            <% if ['.xls', '.xlsx'].include?(file_extension) %>
              <i class="bi bi-file-earmark-spreadsheet me-2"></i>

            <% elsif file_extension == '.pdf' %>
              <i class="bi bi-file-earmark-pdf me-2"></i>

            <% elsif ['.doc', '.docx'].include?(file_extension) %>
              <i class="bi bi-file-earmark-word me-2"></i>

            <% elsif ['.jpg', '.jpeg', '.png'].include?(file_extension) %>
              <i class="bi bi-file-earmark-image me-2"></i>

            <% elsif file_extension == '.txt' %>
              <i class="bi bi-file-earmark-text me-2"></i>

            <% else %>
              <i class="bi bi-file-earmark me-2"></i>
            <% end %>

            <%= link_to file.filename.to_s, url_for(file), target: "_blank", class: "text-decoration-none fw-bold" %>
          </div>
          <small class="text-muted"><%= number_to_human_size(file.byte_size) %></small>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if current_user.role == 'creator' %>
  <div class="mt-4 d-flex">
    <% if @project.status == 'draft' %>
      <%= button_to t('project.show.status_btn.published'), publish_project_path(@project), method: :patch, class: "btn btn-success me-2", form: { class: "d-inline" } %>
    <% elsif @project.status == 'published' %>
      <%= button_to t('project.show.status_btn.archive'), archive_project_path(@project), method: :patch, class: "btn btn-secondary me-2", form: { class: "d-inline" } %>
    <% elsif @project.status == 'archived' %>
      <%= button_to t('project.show.status_btn.in_preparation'), revert_to_draft_project_path(@project), method: :patch, class: "btn btn-warning me-2", form: { class: "d-inline" } %>
    <% end %>
  </div>
  <% end %>

  <hr class="mt-4 mb-3"> 

  <div class="d-flex justify-content-between align-items-center mb-3">
    <h4><%= t('project.show.title_questions') %></h4>
    <% if current_user.role == 'creator' %>
      <%= link_to t('project.show.btn_add_question'), new_project_question_path(@project), class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
  <% if @project.questions.any? %>
    <% if current_user.role == 'expert' %>
      <%= form_with url: project_ratings_path(@project), method: :post, local: false, id: "ratings-form", data: { turbo: false } do %>
        <div id="rating-success" class="alert alert-success d-none mb-2" role="alert">
          <%= t('project.show.ratings_saved') %>
        </div>
        <ul class="list-group mb-3">
          <% @project.questions.each do |question| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div>
                    <strong><%= question.question %></strong><br>
                    <span id="question-<%= question.id %>" class="average-container">
                      <% if question.average_rating.present? %>
                        <span class="badge <%= question.average_rating_color %> mt-1 average-badge">
                          <%= t('project.show.label_avg_rating') %>: <%= question.average_rating %>
                        </span>
                      <% else %>
                        <span class="badge bg-secondary mt-1 average-badge">
                          <%= t('project.show.label_no_ratings') %>
                        </span>
                      <% end %>
                    </span>
                  </div>
                
                  <div>
                    <% existing_rating = question.ratings.find_by(expert_id: current_user.id) %>
                    <%= select_tag "ratings[#{question.id}]",
                          options_for_select((1..10).to_a, existing_rating&.value),
                          class: "form-select form-select-sm",
                          prompt: t('project.show.label_mask_rating') %>
                  </div>
            </li>
          <% end %>
        </ul>
        <%= submit_tag t('project.show.btn_save_ratings'), class: "btn btn-success" %>
      <% end %>

      <% elsif current_user.role == 'creator' %>
      <ul class="list-group mb-3">
        <% @project.questions.each do |question| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
              <strong><%= question.question %></strong>
              <br>
              <% if question.average_rating.present? %>
                <span class="badge <%= question.average_rating_color %> mt-1"><%= t('project.show.label_avg_rating') %>: <%= question.average_rating %></span>
              <% else %>
                <span class="badge bg-secondary mt-1"> <%= t('project.show.label_no_ratings') %></span>
              <% end %>
            </div>
            <div>
              <%= link_to t('project.show.btn_edit_question'), edit_project_question_path(@project, question), class: "btn btn-sm btn-outline-warning me-2" %>
              <%= button_to t('project.show.btn_del_question'), project_question_path(@project, question), method: :delete, data: { confirm: 'Удалить этот вопрос?' }, class: "btn btn-sm btn-outline-danger", form: { class: "d-inline" } %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
    
  <% else %>
    <p class="text-muted"><%= t('project.show.label_no_questions') %></p>
  <% end %>

  <hr class="my-4">

  <% if current_user.role == 'expert' %>
    <h4><%= t('project.show.title_comment') %></h4>
    <%= form_with url: project_comments_path(@project), method: :post, local: true do %>
      <div class="mb-3">
        <%= text_area_tag "comment[content]", @project.comments.find_by(user: current_user)&.content, class: "form-control", rows: 5, placeholder: t('project.show.label_mask_comment') %>
      </div>
      <%= submit_tag t('project.show.btn_save_comment'), class: "btn btn-success mb-2" %>
    <% end %>

    <% if @project.comments.find_by(user: current_user).present? %>
      <%= button_to t('project.show.btn_del_comment'), project_comment_path(@project, @project.comments.find_by(user: current_user)), method: :delete, data: { confirm: "Удалить комментарий?" }, class: "btn btn-sm btn-outline-danger mb-2" %>
    <% end %>

    <hr class="my-4">

    <h4><%= t('project.show.title_comments') %></h4>
    <% if @project.comments.any? %>
      <ul class="list-group my-3">
        <% @project.comments.includes(:user).each do |comment| %>
          <li class="list-group-item">
            <div class="d-flex justify-content-between">
              <strong><%= "#{comment.user.first_name} #{comment.user.last_name}" %></strong>
              <small class="text-muted"><%= comment.updated_at.strftime("%d.%m.%Y %H:%M") %></small>
            </div>
            <p><%= simple_format(comment.content) %></p>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-muted"><%= t('project.show.label_no_comments') %></p>
    <% end %>


  <% elsif current_user.role == 'creator' %>
    <h4><%= t('project.show.title_comments') %></h4>
    <% if @project.comments.any? %>
      <ul class="list-group my-3">
        <% @project.comments.includes(:user).each do |comment| %>
          <li class="list-group-item">
            <div class="d-flex justify-content-between">
              <strong><%= "#{comment.user.first_name} #{comment.user.last_name}" %></strong>
              <small class="text-muted"><%= comment.updated_at.strftime("%d.%m.%Y %H:%M") %></small>
            </div>
            <p><%= simple_format(comment.content) %></p>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-muted"><%= t('project.show.label_no_comments') %></p>
    <% end %>
  <% end %>

</div>